/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.Reader;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import pm.vo.memberVO;

import javax.swing.*;

/**
 * @author 쌍용교육센터
 */
public class findFrame extends javax.swing.JFrame {
    SqlSessionFactory factory;// 펙토리를 활용하기 위해 갖고옴
    JCheckBox teacherBox;
    SqlSession ss;
    memberVO vo;
    String idCode;
    String pwID;
    String pwCode;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(findFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public findFrame() throws IOException {

        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


        this.setLocation(870, 270);
        init();


        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                idCode = new String(idCode_input.getPassword()); //ID찾기란의 백업코드 문자추출
                pwID = pwID_input.getText().trim(); // PW찾기란의 아이디 문자추출
                pwCode = new String(pwCode_input.getPassword()); // PW찾기란의 백업코드 문자추출
                ss = factory.openSession();

                // 강사용 체크 check yse or no
                if (teacherBox.isSelected()) {
                    check_T_or_F("find_ad_ID", "find_ad_PW","강사 ID: ","강사 PW: ");
                    ss.close();
                } else {// 체크박스 선택안되면 학생의 아이디와 비밀번호 찾기
                    check_T_or_F("member.find_st_ID", "member.find_st_PW","학생 ID: ","학생 PW: " );// check false일 때
                    ss.close();
                }// 체크박스 선택 여부의 마지막

            }//
        });//찾기 버튼 마지막*******************************

        jButton4.addActionListener(new ActionListener() {//Close 버튼 클릭
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

    }// 생성자 마지막


    private void check_T_or_F(String target1, String target2, String Ai_or_Si, String Ap_or_Sp) { //
        if (pwID_input.getText().trim().length() < 1 && pwCode.trim().length() < 1) {// 공백제거..???

            vo = ss.selectOne(target1, idCode);

            if (vo != null) {
                member_not_null(vo.getMem_id(), Ai_or_Si);// 함수 %%%%
            } else {
                member_null(); // 함수 %%%%&&&&
            }

        }//여기 까지 아이디찾기 ****************************************************
        else if (idCode.trim().length() < 1) {

            Map<String, String> m = new HashMap<>();
            m.put("ID", pwID);
            m.put("bc", pwCode);
            vo = ss.selectOne(target2, m);

            if (vo != null) {
                member_not_null(vo.getMem_pw(), Ap_or_Sp); // 함수 %%%%&&&&

            } else {
                member_null(); // 함수 %%%%&&&&
            }
        } else {
            JOptionPane.showMessageDialog(findFrame.this, "입력 오류 입니다");
        }
    }

    private void member_not_null(String get, String Ai_or_Si) {
        String find = get;
        JOptionPane.showMessageDialog(findFrame.this, Ai_or_Si + find);
        settext();

    }
    private void member_null(){
        JOptionPane.showMessageDialog(findFrame.this,
                "일치하는 정보가 없습니다.",
                "검색 실패", JOptionPane.WARNING_MESSAGE);
        settext();// 함수임 텍스트 필드 리셋

    }

    private void init() throws IOException {
        Reader r = Resources.getResourceAsReader("pm/config/conf.xml");
        factory = new SqlSessionFactoryBuilder().build(r);
        r.close();
    }

    private void settext() {
        idCode_input.setText("");
        pwID_input.setText("");
        pwCode_input.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idCode_input = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pwID_input = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pwCode_input = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new java.awt.GridLayout());
        jPanel6.add(jPanel17);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setFont(new java.awt.Font("새굴림", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("  Find ID");
        jPanel2.add(jLabel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("  Backup Code:");
        jPanel4.add(jLabel1);

        idCode_input.setColumns(10);
        jPanel4.add(idCode_input);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.GridLayout(3, 0));
        jPanel9.add(jPanel11);
        jPanel9.add(jSeparator1);
        jPanel9.add(jSeparator2);

        jPanel5.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("새굴림", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("  Find PW");
        jPanel12.add(jLabel2);

        jPanel10.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("                       ID:");
        jPanel14.add(jLabel3);

        pwID_input.setColumns(10);
        jPanel14.add(pwID_input);

        jPanel13.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("  Backup Code:");
        jPanel16.add(jLabel4);

        pwCode_input.setColumns(10);
        jPanel16.add(pwCode_input);

        jPanel15.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        teacherBox = new JCheckBox("강사");
        teacherBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(teacherBox);

        jButton1.setText("Find");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(jButton1);

        jButton4.setText("Close");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(jButton4);

        jPanel7.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new findFrame().setVisible(true);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField idCode_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pwCode_input;
    private javax.swing.JTextField pwID_input;
    // End of variables declaration//GEN-END:variables
}
